apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kro:platform.example.com
  labels:
    rbac.kro.run/aggregate-to-controller: "true"
rules:
  - apiGroups:
      - platform.example.com
    resources:
      - globalwidgets
      - globalwidgets/status
      - globalwidgets/finalizers
      - regionalwidgetrequests
      - regionalwidgetrequests/status
      - regionalwidgetrequests/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
