widgetOperator:
  enabled: true
  replicas: 1
  readyDelay: 2s
  image:
    repository: widget-operator
    tag: local
    pullPolicy: IfNotPresent
  resources:
    requests: { cpu: 20m, memory: 32Mi }
    limits: { cpu: 200m, memory: 128Mi }