apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: binding-controller
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: binding-controller
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: rook-ceph-mgr
  endpoints:
    - port: http-metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - rook-ceph